version: '3.8'

services: 
  #Backend API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      # switch uri to environment variable in production
      POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker
      API_KEY: $CLARIFAI_KEY
    ports: 
      #detect port in production instead of hard coding
      - "3000:3000"
    volumes: 
      - ./:/usr/src/smart-brain-api
      - /usr/src/smart-brain-api/node_modules

  # Postgres
  postgres: 
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    container_name: postgres
    build: ./postgres
    ports: 
      - "5432:5432"